apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: agenda-angular
  name: agenda-angular
  annotations:
      openshift.io/image.insecureRepository: "true"
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: wvm-srv6.luminy.univ-amu.fr/polytechprojet/agenda:0.2.0
    generation: null
    importPolicy:
        insecure: true
    name: 0.2.0
status:
  dockerImageRepository: ""
