apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: agenda-angular
  name: agenda-angular
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    io.kompose.service: agenda-angular
status:
  loadBalancer: {}
