apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --provider openshift --file docker-compose.yml
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    io.kompose.service: auth
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: db
        image: ' '
        name: auth
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - auth
      from:
        kind: ImageStreamTag
        name: auth:0.1.2
    type: ImageChange
status: {}
