apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  containers:
  - image: wvm-srv6.luminy.univ-amu.fr/polytechprojet/node:0.0.1
    name: auth
    ports:
    - containerPort: 3000
    resources: {}
  restartPolicy: OnFailure
status: {}
