apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: wvm-srv6.luminy.univ-amu.fr/polytechprojet/node:0.1.2
    generation: null
    importPolicy: {}
    name: 0.1.2
status:
  dockerImageRepository: ""
