apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --provider openshift --file docker-compose.yml
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: myadmin
  name: myadmin
spec:
  replicas: 1
  selector:
    io.kompose.service: myadmin
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: myadmin
    spec:
      containers:
      - image: ' '
        name: myadmin
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - myadmin
      from:
        kind: ImageStreamTag
        name: myadmin:0.1.0
    type: ImageChange
status: {}
