apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe --provider openshift --file docker-compose.yml
      convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: myadmin
  name: myadmin
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 4000
  selector:
    io.kompose.service: myadmin
status:
  loadBalancer: {}
