apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: myadmin
  name: myadmin
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: phpmyadmin/phpmyadmin
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
