apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: myadmin
  name: myadmin
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: wvm-srv6.luminy.univ-amu.fr/polytechprojet/phpmyadmin:0.1.0
    generation: null
    importPolicy: {}
    name: 0.1.0
status:
  dockerImageRepository: ""
