apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose --provider openshift --file docker-compose.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: myadmin
  name: myadmin
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: myadmin
status:
  loadBalancer: {}
